#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt APPEND_HISTORY
export KEYTIMEOUT=1
export TERM=screen-256color

source "~/dotfiles/tmuxinator.zsh" 
export PATH=/usr/local/cuda-5.5/bin:/home/local/3PILLAR/rszabo/.local/bin:/usr/local/bin:/usr/local/sbin:/home/local/3PILLAR/rszabo/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export LD_LIBRARY_PATH=/usr/local/cuda-5.5/lib64:
export PYLEARN2_DATA_PATH=~/data
